# Numpy

### 1) Create Array
### 2) Array Indexing - Access Array Elements
### 3) Array Slicing
### 4) Useful Commands
### 5) Iterating the Arrays
### 6) Joining Array
### 7) Splitting Array
### 8) Searching Arrays
### 9) Sorting Arrays
### 10) Filtering Arrays
### 11) Random Numbers in NumPy
### 12a) Simple Arithmetic
### 12b) Decimals Rounding
### 12c) Summation
### 12d Product
### 12e) Differences
### 12f) Set Operations

In [1]:
import numpy as np

# 1) Create Array

In [2]:
arr = np.array(42)
arr

array(42)

In [3]:
arr1 = np.array([20,40,60,80,100])
arr1

array([ 20,  40,  60,  80, 100])

In [57]:
arr2 = np.array([[20,40],[60,80]])
arr2

array([[20, 40],
       [60, 80]])

In [58]:
arr3 = np.array(
    [
        [
            [20,40,60], [80,100,120]
        ], 
        
        [
            [140,160,180], [200,220,240]
        ]
    ]
)
arr3

array([[[ 20,  40,  60],
        [ 80, 100, 120]],

       [[140, 160, 180],
        [200, 220, 240]]])

In [59]:
arr3 = np.array([[[20,40,60], [80,100,120]], [[140,160,180], [200,220,240]]])
arr3

array([[[ 20,  40,  60],
        [ 80, 100, 120]],

       [[140, 160, 180],
        [200, 220, 240]]])

In [62]:
arr4 = np.array([1, 2, 3, 4], ndmin=20)
arr4

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4]]]]]]]]]]]]]]]]]]]])

# 2) Array Indexing - Access Array Elements

In [64]:
# Access 1-D Arrays

print(arr1[0])

20


In [65]:
print(arr1[4])

100


In [66]:
print(arr1[-1])

100


In [67]:
#Access 2-D Arrays: arr[row,col]

print(arr2[0,0])

20


In [68]:
print(arr2[1,1])

80


In [69]:
print(arr2[-1,0])

60


In [72]:
# Access 3-D Arrays : arr[arr#,row,col]

print(arr3[0,1,2])  # 0th array, 1st row, 2nd column

120


In [73]:
print(arr3[1,0,1])

160


# 3) Array Slicing : [start:end] or [start:end:step]

In [75]:
arr1[:]

array([ 20,  40,  60,  80, 100])

In [76]:
arr1[1:3]

array([40, 60])

In [77]:
arr1[:3]

array([20, 40, 60])

In [78]:
arr1[1:]

array([ 40,  60,  80, 100])

In [79]:
arr1[0:5:2]

array([ 20,  60, 100])

In [80]:
arr1[0:5:3]

array([20, 80])

In [82]:
arr1[-3:-1]

array([60, 80])

In [85]:
arr1[-3:]

array([ 60,  80, 100])

In [89]:
arr3[:]

array([[[ 20,  40,  60],
        [ 80, 100, 120]],

       [[140, 160, 180],
        [200, 220, 240]]])

In [91]:
arr3[1,1,0:2]

array([200, 220])

# 4) Useful Commands

In [101]:
#What is the object type ?

type(arr1)

numpy.ndarray

In [102]:
# How many dimenstional array ? 

print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [94]:
arr1

array([ 20,  40,  60,  80, 100])

In [103]:
# What is the shape of the array ?

print(arr1.shape)

(5,)


In [96]:
arr2

array([[20, 40],
       [60, 80]])

In [97]:
arr2.shape

(2, 2)

In [98]:
arr3

array([[[ 20,  40,  60],
        [ 80, 100, 120]],

       [[140, 160, 180],
        [200, 220, 240]]])

In [99]:
arr3.shape

(2, 2, 3)

In [104]:
# Can we reshape the array ? 
arr_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
newarr = arr_1.reshape(4,3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [107]:
newarr2 = newarr.reshape(-1)
newarr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 5) Iterating the Arrays

In [109]:
arr1

array([ 20,  40,  60,  80, 100])

In [110]:
for i in arr1:
    print (i)

20
40
60
80
100


In [111]:
arr2

array([[20, 40],
       [60, 80]])

In [112]:
for i in arr2:
    print(i)

[20 40]
[60 80]


In [113]:
arr3

array([[[ 20,  40,  60],
        [ 80, 100, 120]],

       [[140, 160, 180],
        [200, 220, 240]]])

In [114]:
for i in arr3:
    print(i)

[[ 20  40  60]
 [ 80 100 120]]
[[140 160 180]
 [200 220 240]]


In [119]:
for i in arr2:
    for j in i:
        print(j)

20
40
60
80


In [123]:
for i in arr3:
    for j in i:
        for k in j:
            print(k)

20
40
60
80
100
120
140
160
180
200
220
240


In [125]:
#Enumerate Iteration

for id, i in np.ndenumerate(arr3):
    print(id, i)

(0, 0, 0) 20
(0, 0, 1) 40
(0, 0, 2) 60
(0, 1, 0) 80
(0, 1, 1) 100
(0, 1, 2) 120
(1, 0, 0) 140
(1, 0, 1) 160
(1, 0, 2) 180
(1, 1, 0) 200
(1, 1, 1) 220
(1, 1, 2) 240


# 6) Joining Array

In [126]:
var1 = np.array([1, 2, 3])
var2 = np.array([4, 5, 6])
var3 = np.concatenate((var1, var2))
var3

array([1, 2, 3, 4, 5, 6])

In [134]:
arr1 = np.array([[1, 2], [3, 4]])
print(arr1,'\n')

arr2 = np.array([[5, 6], [7, 8]])
print(arr2,'\n')

arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3,'\n')

arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


In [137]:
arr1 = np.array([1, 2, 3])
print(arr1,'\n')

arr2 = np.array([4, 5, 6])
print(arr2,'\n')

arr3 = np.stack((arr1, arr2), axis=0)
print(arr3,'\n')

arr4 = np.stack((arr1, arr2), axis=1)
print(arr4)

[1 2 3] 

[4 5 6] 

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]]


In [138]:
arr1 = np.array([1, 2, 3])
print(arr1,'\n')

arr2 = np.array([4, 5, 6])
print(arr2,'\n')

arr3 = np.vstack((arr1, arr2))
print(arr3,'\n')

[1 2 3] 

[4 5 6] 

[[1 2 3]
 [4 5 6]] 



In [139]:
arr1 = np.array([1, 2, 3])
print(arr1,'\n')

arr2 = np.array([4, 5, 6])
print(arr2,'\n')

arr3 = np.dstack((arr1, arr2))
print(arr3,'\n')

[1 2 3] 

[4 5 6] 

[[[1 4]
  [2 5]
  [3 6]]] 



# 7) Splitting Array

In [140]:
#Splitting 1-D Array

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [143]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4) #If the array has less elements than required, it will adjust from the end accordingly.

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [144]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5]


In [145]:
#Splitting 2-D Array

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

print(arr,'\n')

newarr = np.array_split(arr, 3)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [147]:
# Split along column wise

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

print(arr,'\n')

newarr = np.array_split(arr, 3, axis=1) #axis = 1 means column wise

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# 8) Searching Arrays

In [148]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [149]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)  #Find the indexes where the values are even

print(x)

(array([1, 3, 5, 7]),)


In [153]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7) # searches from left to right

print(x)

1


In [152]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')  # searches from left to right

print(x)

2


In [154]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])  # multiple values search

print(x)

[1 2 3]


# 9) Sorting Arrays

In [155]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [156]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [157]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [160]:
# sort 2-D array

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(arr,'\n')

print(np.sort(arr))

[[3 2 4]
 [5 0 1]] 

[[2 3 4]
 [0 1 5]]


# 10) Filtering Arrays

In [161]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [171]:
arr = np.array([41, 42, 43, 44])

filtered_array_even = [] #create an empty List
filtered_array_odd = [] #create an empty List

for i in arr:
    if i%2 == 0:
        filtered_array_even.append(i)
    else:
        filtered_array_odd.append(i)

print(filtered_array_even)
print(filtered_array_odd)
        

[42, 44]
[41, 43]


In [174]:
arr = np.array([41, 42, 43, 44])

var1 = arr%2 == 0
var2 = arr%2 != 0

print (var1, '\n', var2, '\n')

filtered_array_even = arr[var1]
filtered_array_odd = arr[var2]

print(filtered_array_even)
print(filtered_array_odd)

[False  True False  True] 
 [ True False  True False] 

[42 44]
[41 43]


# 11) Random Numbers in NumPy

In [175]:
from numpy import random


In [178]:
x = random.randint(100) # generates random int

print(x)

60


In [181]:
x = random.rand()  # generates random float

print(x)

0.018839913751017123


In [190]:
# generates random 1-D array

x1=random.randint(100, size=(5)) 
x2=random.rand(5)

print(x1,'\n')
print(x2)

[26 84 54 95 11] 

[0.0875342  0.01119274 0.65102342 0.61805483 0.60248158]


In [191]:
# generates random 2-D array

x1=random.randint(100, size=(3,5)) 
x2=random.rand(3,5)

print(x1,'\n')
print(x2)

[[17 48 57 39 23]
 [24 92 50 49 45]
 [67 15 61 12 33]] 

[[0.70974419 0.24937079 0.79112699 0.53731748 0.85742738]
 [0.40126576 0.30453443 0.06457813 0.11128625 0.23814696]
 [0.99512672 0.65772429 0.06795942 0.45700769 0.3391969 ]]


In [199]:
# generate random number from an array

x = random.choice([3, 5, 7, 9])  # choice takes only 1-D array as input.

print(x)

7


In [200]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 9 3 5 3]
 [7 3 7 9 5]
 [5 5 7 3 7]]


# 12) NumPy ufuncs

# 12a ) Simple Arithmetic

In [201]:
#add
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [202]:
#subtract
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [203]:
#multiply
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [204]:
#divide
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [206]:
#power
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [207]:
# mod, remainder 
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr1 = np.mod(arr1, arr2)
newarr2 = np.remainder(arr1, arr2)

print(newarr1,'\n',newarr2)

[ 1  6  3  0  0 27] 
 [ 1  6  3  0  0 27]


In [209]:
# Quotient & Remainder 

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [211]:
# absolute 
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


# 12b) Decimals Rounding

In [213]:
# Truncate, fix

arr1 = np.trunc([-3.1666, 3.6667])

print(arr1,'\n')

arr2 = np.fix([-3.1666, 3.6667])

print(arr2)

[-3.  3.] 

[-3.  3.]


In [216]:
# Rounding

arr1 = np.around(3.1666, 1)
arr2 = np.around(3.1666, 2)
arr3 = np.around(3.1666, 3)

print(arr1,'\n',arr2,'\n',arr3)

3.2 
 3.17 
 3.167


In [217]:
# Floor - rounds off decimal to nearest lower integer

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


In [218]:
# Ceil - rounds off decimal to nearest upper integer

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


# 12c) Summation

In [219]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2]) # overall sum

print(newarr)

12


In [224]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=0) # supposed to be row level but happening at column level - Doubt 

print(newarr)

[2 4 6]


In [223]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1) # supposed to be column level but happening at row level - Doubt 

print(newarr)

[6 6]


In [225]:
# Cummulative Sum

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


# 12d Product 

In [226]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)  # 1*2*3*4 = 24

print(x)

24


In [227]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])  # 1*2*3*4*5*6*7*8

print(x)

40320


In [229]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=0) # supposed to be row level but happening at column level - Doubt 

print(newarr)

[ 5 12 21 32]


In [231]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1) # supposed to be column level but happening at row level - Doubt

print(newarr)

[  24 1680]


In [234]:
#Cummulative Product

arr = np.array([1, 2, 3, 4])

newarr = np.cumprod(arr)   # [1, 1*2, 1*2*3, 1*2*3*4]

print(newarr)

[ 1  2  6 24]


# 12e) Differences

In [236]:
arr = np.array([1, 2, 3, 4])

newarr = np.diff(arr)  # [2-1, 3-2, 4-3]

print(newarr)

[1 1 1]


# 12f) Set Operations

In [237]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [238]:
# union

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [240]:
# intersection

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr1 = np.intersect1d(arr1, arr2, assume_unique=True) # speed up computation
newarr2 = np.intersect1d(arr1, arr2)

print(newarr1,'\n',newarr2)

[3 4] 
 [3 4]


In [243]:
# set difference 

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr1 = np.setdiff1d(set1, set2, assume_unique=True)  # set1-set2
newarr2 = np.setdiff1d(set2, set1, assume_unique=True)  # set2-set1

print(newarr1,'\n',newarr2)

[1 2] 
 [5 6]


In [245]:
#Symmetric Difference

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
