# Loss, Cost Function 

Source" https://www.youtube.com/watch?v=E1yyaLRUnLo&list=PLeo1K3hjS3uu7CxAacxVndI4bE_o3BDtO&index=11

In [20]:
import numpy as np

In [3]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

<h3 style='color:blue'>Implement Mean Absolute Error</h3>

In [10]:
def mae(y_predicted, y_true):
    
    total_error = 0
    
    for yp, yt in zip(y_predicted, y_true): # zip is required to go through 2 arrays together. 
        
        total_error += abs(yp - yt)  # total_error = total_error + abs(yp - yt) 
        
    print("Total error is:",total_error)
    
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)


In [11]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


**Implement same thing using numpy in much easier way**

In [6]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [7]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [12]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [13]:
mae_np(y_predicted, y_true)

0.5

<h3 style='color:blue'>Implement Log Loss or Binary Cross Entropy</h3>

In [14]:
np.log([0])  # log of '0' is undefined. hence we need to replace 0 with value very nearer to 0, which is epsilon below.

<ipython-input-14-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [16]:
epsilon = 1e-15

epsilon

1e-15

In [21]:
np.log(epsilon)  # doesnt result in infinity. 

-34.538776394910684

In [22]:
y_predicted

array([1, 1, 0, 0, 1])

In [24]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [25]:
1-epsilon # log of '1' is zero, hence need to replace 1 with value nearest to 1 i.e 1-epsilon

0.999999999999999

In [26]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [27]:
y_predicted_new = np.array(y_predicted_new)

y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [28]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [29]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [31]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [32]:
log_loss(y_true, y_predicted)

17.2696280766844

In [ ]:
# we have done all this to understand the concept. In tensfor flow we have readymade functions for this. 

<h3 style='color:purple'>Exercise</h3>

Implement mean squared error (or MSE) in two ways,

1) Without using numpy (i.e. using plain python)

2) With the use of numpy

[Solution](https://github.com/codebasics/py/tree/master/DeepLearningML/5_loss/loss_function_exercise_solution.ipynb)