Source: https://www.youtube.com/watch?v=kKDYtZfriI8

In [1]:
# Only below portion is taken from the source. 

In [2]:
#pip install keras

Note: you may need to restart the kernel to use updated packages.


In [3]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [4]:
# define documents
Sent = ['Hello, how are you',
        'how are you',
        'how are you doing',
        'I am doing great',
        'I am doing good',
        'I am good']

In [13]:
# defining class labels i.e target variable

sent_labels = array([1,1,1,0,0,0])  # here 1 means question type statements. 0 means answer type statements. 

In [5]:
# integer encoding of the documents

my_vocab_size = 30

encoded_sent = [one_hot(i, my_vocab_size) for i in Sent]

print(encoded_sent)

[[26, 11, 4, 20], [11, 4, 20], [11, 4, 20, 23], [26, 21, 23, 3], [26, 21, 23, 26], [26, 21, 26]]


In [6]:
# padding documents to a max length =5 . Padding is performed to make all arrays of same size. 

length = 5

padded_sent = pad_sequences(encoded_sent, maxlen=length, padding='pre') # 'pre' means pad the 0 in the beginning.

print(padded_sent)

[[ 0 26 11  4 20]
 [ 0  0 11  4 20]
 [ 0 11  4 20 23]
 [ 0 26 21 23  3]
 [ 0 26 21 23 26]
 [ 0  0 26 21 26]]


In [8]:
# defining the model

mymodel = Sequential()

mymodel.add(Embedding(my_vocab_size, 8, input_length=length))

mymodel.add(Flatten())

mymodel.add(Dense(1, activation='sigmoid'))

In [9]:
# compiling the model

mymodel.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [25]:
# fiting  the model

mymodel.fit(padded_sent, sent_labels, epochs=25)

Epoch 1/25
1/1 [==============================] - 0s 3ms/step - loss: 0.6371 - accuracy: 1.0000
Epoch 2/25
1/1 [==============================] - 0s 2ms/step - loss: 0.6348 - accuracy: 1.0000
Epoch 3/25
1/1 [==============================] - 0s 2ms/step - loss: 0.6326 - accuracy: 1.0000
Epoch 4/25
1/1 [==============================] - 0s 3ms/step - loss: 0.6303 - accuracy: 1.0000
Epoch 5/25
1/1 [==============================] - 0s 3ms/step - loss: 0.6279 - accuracy: 1.0000
Epoch 6/25
1/1 [==============================] - 0s 2ms/step - loss: 0.6256 - accuracy: 1.0000
Epoch 7/25
1/1 [==============================] - 0s 3ms/step - loss: 0.6233 - accuracy: 1.0000
Epoch 8/25
1/1 [==============================] - 0s 4ms/step - loss: 0.6209 - accuracy: 1.0000
Epoch 9/25
1/1 [==============================] - 0s 3ms/step - loss: 0.6186 - accuracy: 1.0000
Epoch 10/25
1/1 [==============================] - 0s 3ms/step - loss: 0.6162 - accuracy: 1.0000
Epoch 11/25
1/1 [======================

In [26]:
# evaluate the model

modelloss, modelaccuracy = mymodel.evaluate(padded_sent, sent_labels, verbose=0)

print('Accuracy: %f' % (modelaccuracy*100))

Accuracy: 100.000000


In [27]:
# since we have less data we got accuract as 1. 

### Prediction

In [28]:
mysent_to_predict = ['how are you Suman',
        'I am good']

# we have created one as question and one sentence as answer. 

In [29]:
# integer encode the documents

vocab_size = 30

encoded = [one_hot(d, vocab_size) for d in mysent_to_predict]

print(encoded)

[[11, 4, 20, 27], [26, 21, 26]]


In [30]:
# pad documents to a max length of 5 words

max_length = 5

mypadded = pad_sequences(encoded, maxlen=max_length, padding='pre')

print(mypadded)

[[ 0 11  4 20 27]
 [ 0  0 26 21 26]]


In [32]:
mymodel.predict_classes(mypadded)  

array([[1],
       [0]], dtype=int32)

In [ ]:
# we can see that model has predicted correctly. Class 1 means question, Class 0 means answer. 

In [ ]:
# when we trained the model with epoch = 30 , it gave wrong prediction, then after reducing epoch to 25 it correctly
# predicted. So some times we need to increase or decrease the epoch and train again. 